// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZZOYxxqfu9XC_FASPgiDnLD4VwTttvVg',
    appId: '1:812086249719:web:e2003e99847440b789abf2',
    messagingSenderId: '812086249719',
    projectId: 'chat-app-70616',
    authDomain: 'chat-app-70616.firebaseapp.com',
    storageBucket: 'chat-app-70616.appspot.com',
    measurementId: 'G-VNPPEV8NSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23tA3ywQbMmbV2eiEQGnYQFh10jzNuRc',
    appId: '1:812086249719:android:24a8f8137711533989abf2',
    messagingSenderId: '812086249719',
    projectId: 'chat-app-70616',
    storageBucket: 'chat-app-70616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0LqFHiggPxNL5ITPFPRfy-bTi16UKOF8',
    appId: '1:812086249719:ios:9f03ecff3cec896089abf2',
    messagingSenderId: '812086249719',
    projectId: 'chat-app-70616',
    storageBucket: 'chat-app-70616.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0LqFHiggPxNL5ITPFPRfy-bTi16UKOF8',
    appId: '1:812086249719:ios:9f03ecff3cec896089abf2',
    messagingSenderId: '812086249719',
    projectId: 'chat-app-70616',
    storageBucket: 'chat-app-70616.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZZOYxxqfu9XC_FASPgiDnLD4VwTttvVg',
    appId: '1:812086249719:web:c8821ef1578d096b89abf2',
    messagingSenderId: '812086249719',
    projectId: 'chat-app-70616',
    authDomain: 'chat-app-70616.firebaseapp.com',
    storageBucket: 'chat-app-70616.appspot.com',
    measurementId: 'G-J27M0WWTP1',
  );
}
